include classpath("application.conf")

node-address {
  protocol = http
  host = "elasticmq"
  port = 9324
  context-path = ""
}

rest-sqs {
  enabled = true
  bind-port = 9324
  bind-hostname = "0.0.0.0"
  sqs-limits = strict
}

queues {
  luminascale-events-dlq {
    defaultVisibilityTimeout = 60 seconds
    delay = 0 seconds
    receiveMessageWait = 0 seconds
  }
  luminascale-events {
    defaultVisibilityTimeout = 60 seconds
    delay = 0 seconds
    receiveMessageWait = 10 seconds
    deadLettersQueue {
      name = "luminascale-events-dlq"
      maxReceiveCount = 5
    }
  }
}

